### ISSUE TITLE
App is just crashing after a while

### ISSUE THREAD

**Issue by NathanBnm** [cassidyjames/principles#27]
Since last update the app is not starting anymore. It's just appear in the dock without launching anything and finally crashes. I tried to open it from Terminal and that's what I get:

`$ com.github.cassidyjames.principles`

`(com.github.cassidyjames.principles:12013): GLib-GIO-ERROR **: 19:36:40.709: Settings schema 'com.github.cassidyjames.principles' is not installed`

Maybe better with a screenshot:
![image](https://user-images.githubusercontent.com/45366162/51931600-87968f00-23fd-11e9-8cae-8ae0e66017b5.png)

**Comment by cassidyjames** [comment]
@NathanBnm ah I see the issue. Not really sure how that happened, but fixed in https://github.com/cassidyjames/principles/commit/770cfbd2a71dec169c7dd2cff4cf1d86a90fbdc4 which has been submitted to AppCenter.

**Comment by NathanBnm** [comment]
@cassidyjames I just installed it from AppCenter, and also try to reinstall it after manual uninstall. But the result is the same.

I didn't try to complete by myself. But you know there is some issues with AppCenter for now. If you see PR in AppCenter repository, it will apparently fix them.
