### ISSUE TITLE
Minmal build requirements

### ISSUE THREAD

**Issue by probonopd** [cassidyjames/principles#9]
Can this be built on Ubuntu 14.04 and if so, how?

**Comment by cassidyjames** [comment]
@probonopd I have no idea, but I've added build instructions to the README.

**Comment by probonopd** [comment]
Thanks for the clarification, apparently this is not for Desktop Linux in general but rather specifically for elementary OS only. While I like elementary OS (and very much so) I don't think writing applications specifically for one Linux distribution only is a particularly good thing, as we might end up in having to run a particular distribution just to run a particular application.

**Comment by cassidyjames** [comment]
@probonopd there's nothing actively preventing you from building it for any other OS, but I don't have the time and resources to test it on every possible OS, including a four-year-old release of Ubuntu. But as I mentioned on Twitter, the code is completely open source and you're welcome to port it to whatever you'd like.
